[tool.poetry]
name = "OSIBL_correction"
version = "0.1.0"
description = "A package for processing OSIBL IRMS data."
authors = ["Gerard Otiniano <gerardotiniano@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"  # Specify the Python version
pandas = "^1.3.0"  # Adjust to your required version


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
